export const ADD_TO_LIST = 'ADD ITEM TO LIST';
export const PUT_TO_COMPLECTED = 'POP ITEM FROM LIST AND PUT IN COMPLETED LIST';
export const PUT_TO_INCOMPLETE = 'REMOVE ITEM FROM COMPLETED AND ADD IN TODO'